=begin comment

Quicksilver Web API

Further detail about the available features and configuration options can be found in the User Guide.    # Authorization All API calls use bearer authorization except for the following. - POST /api/user/sessions - Uses basic authorization - GET /api/events - Uses query string authorization  # Errors Since the following errors can happen with any API call or with a broad group of API calls, they are documented here rather than for each API call. - 400 (Bad Request). This may occur for any API call, due to the authorization header being malformed. It may also occur due to malformed or incorrect JSON structure of the request body. Other more specific reasons are documented on a per API basis below. - 401 (Unauthenticated) - 403 (Unauthorized). If the user is authenticated as a user with the Standard role, but the API call requires the Admin role. - 500 (Internal Server Error) 

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::ConfigurationApi');

my $api = WWW::OpenAPIClient::ConfigurationApi->new();
isa_ok($api, 'WWW::OpenAPIClient::ConfigurationApi');

#
# cfg_type_dns_get test
#
# uncomment below and update the test
#my $cfg_type_dns_get_type = undef; # replace NULL with a proper value
#my $cfg_type_dns_get_result = $api->cfg_type_dns_get(type => $cfg_type_dns_get_type);

#
# cfg_type_dns_patch test
#
# uncomment below and update the test
#my $cfg_type_dns_patch_type = undef; # replace NULL with a proper value
#my $cfg_type_dns_patch_dns_settings_request = undef; # replace NULL with a proper value
#my $cfg_type_dns_patch_result = $api->cfg_type_dns_patch(type => $cfg_type_dns_patch_type, dns_settings_request => $cfg_type_dns_patch_dns_settings_request);

#
# cfg_type_eth_get test
#
# uncomment below and update the test
#my $cfg_type_eth_get_type = undef; # replace NULL with a proper value
#my $cfg_type_eth_get_result = $api->cfg_type_eth_get(type => $cfg_type_eth_get_type);

#
# cfg_type_eth_patch test
#
# uncomment below and update the test
#my $cfg_type_eth_patch_type = undef; # replace NULL with a proper value
#my $cfg_type_eth_patch_eth_settings_request = undef; # replace NULL with a proper value
#my $cfg_type_eth_patch_result = $api->cfg_type_eth_patch(type => $cfg_type_eth_patch_type, eth_settings_request => $cfg_type_eth_patch_eth_settings_request);

#
# cfg_type_get test
#
# uncomment below and update the test
#my $cfg_type_get_type = undef; # replace NULL with a proper value
#my $cfg_type_get_result = $api->cfg_type_get(type => $cfg_type_get_type);

#
# cfg_type_gps_dyn_platform_model_get test
#
# uncomment below and update the test
#my $cfg_type_gps_dyn_platform_model_get_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_dyn_platform_model_get_result = $api->cfg_type_gps_dyn_platform_model_get(type => $cfg_type_gps_dyn_platform_model_get_type);

#
# cfg_type_gps_dyn_platform_model_put test
#
# uncomment below and update the test
#my $cfg_type_gps_dyn_platform_model_put_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_dyn_platform_model_put_body = undef; # replace NULL with a proper value
#my $cfg_type_gps_dyn_platform_model_put_result = $api->cfg_type_gps_dyn_platform_model_put(type => $cfg_type_gps_dyn_platform_model_put_type, body => $cfg_type_gps_dyn_platform_model_put_body);

#
# cfg_type_gps_keep_on_get test
#
# uncomment below and update the test
#my $cfg_type_gps_keep_on_get_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_keep_on_get_result = $api->cfg_type_gps_keep_on_get(type => $cfg_type_gps_keep_on_get_type);

#
# cfg_type_gps_keep_on_put test
#
# uncomment below and update the test
#my $cfg_type_gps_keep_on_put_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_keep_on_put_body = undef; # replace NULL with a proper value
#my $cfg_type_gps_keep_on_put_result = $api->cfg_type_gps_keep_on_put(type => $cfg_type_gps_keep_on_put_type, body => $cfg_type_gps_keep_on_put_body);

#
# cfg_type_gps_sync_time_get test
#
# uncomment below and update the test
#my $cfg_type_gps_sync_time_get_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_sync_time_get_result = $api->cfg_type_gps_sync_time_get(type => $cfg_type_gps_sync_time_get_type);

#
# cfg_type_gps_sync_time_put test
#
# uncomment below and update the test
#my $cfg_type_gps_sync_time_put_type = undef; # replace NULL with a proper value
#my $cfg_type_gps_sync_time_put_body = undef; # replace NULL with a proper value
#my $cfg_type_gps_sync_time_put_result = $api->cfg_type_gps_sync_time_put(type => $cfg_type_gps_sync_time_put_type, body => $cfg_type_gps_sync_time_put_body);

#
# cfg_type_ird_mode_get test
#
# uncomment below and update the test
#my $cfg_type_ird_mode_get_type = undef; # replace NULL with a proper value
#my $cfg_type_ird_mode_get_result = $api->cfg_type_ird_mode_get(type => $cfg_type_ird_mode_get_type);

#
# cfg_type_ird_mode_put test
#
# uncomment below and update the test
#my $cfg_type_ird_mode_put_type = undef; # replace NULL with a proper value
#my $cfg_type_ird_mode_put_body = undef; # replace NULL with a proper value
#my $cfg_type_ird_mode_put_result = $api->cfg_type_ird_mode_put(type => $cfg_type_ird_mode_put_type, body => $cfg_type_ird_mode_put_body);

#
# cfg_type_outgoing_firewall_rules_get test
#
# uncomment below and update the test
#my $cfg_type_outgoing_firewall_rules_get_type = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_get_result = $api->cfg_type_outgoing_firewall_rules_get(type => $cfg_type_outgoing_firewall_rules_get_type);

#
# cfg_type_outgoing_firewall_rules_name_delete test
#
# uncomment below and update the test
#my $cfg_type_outgoing_firewall_rules_name_delete_type = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_name_delete_name = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_name_delete_result = $api->cfg_type_outgoing_firewall_rules_name_delete(type => $cfg_type_outgoing_firewall_rules_name_delete_type, name => $cfg_type_outgoing_firewall_rules_name_delete_name);

#
# cfg_type_outgoing_firewall_rules_name_patch test
#
# uncomment below and update the test
#my $cfg_type_outgoing_firewall_rules_name_patch_type = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_name_patch_name = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_name_patch_patch_outgoing_firewall_rule = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_name_patch_result = $api->cfg_type_outgoing_firewall_rules_name_patch(type => $cfg_type_outgoing_firewall_rules_name_patch_type, name => $cfg_type_outgoing_firewall_rules_name_patch_name, patch_outgoing_firewall_rule => $cfg_type_outgoing_firewall_rules_name_patch_patch_outgoing_firewall_rule);

#
# cfg_type_outgoing_firewall_rules_post test
#
# uncomment below and update the test
#my $cfg_type_outgoing_firewall_rules_post_type = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_post_outgoing_firewall_rule = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_post_before = undef; # replace NULL with a proper value
#my $cfg_type_outgoing_firewall_rules_post_result = $api->cfg_type_outgoing_firewall_rules_post(type => $cfg_type_outgoing_firewall_rules_post_type, outgoing_firewall_rule => $cfg_type_outgoing_firewall_rules_post_outgoing_firewall_rule, before => $cfg_type_outgoing_firewall_rules_post_before);

#
# cfg_type_port_fwd_entries_get test
#
# uncomment below and update the test
#my $cfg_type_port_fwd_entries_get_type = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_get_result = $api->cfg_type_port_fwd_entries_get(type => $cfg_type_port_fwd_entries_get_type);

#
# cfg_type_port_fwd_entries_name_delete test
#
# uncomment below and update the test
#my $cfg_type_port_fwd_entries_name_delete_type = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_name_delete_name = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_name_delete_result = $api->cfg_type_port_fwd_entries_name_delete(type => $cfg_type_port_fwd_entries_name_delete_type, name => $cfg_type_port_fwd_entries_name_delete_name);

#
# cfg_type_port_fwd_entries_name_patch test
#
# uncomment below and update the test
#my $cfg_type_port_fwd_entries_name_patch_type = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_name_patch_name = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_name_patch_patch_port_fwd_entry = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_name_patch_result = $api->cfg_type_port_fwd_entries_name_patch(type => $cfg_type_port_fwd_entries_name_patch_type, name => $cfg_type_port_fwd_entries_name_patch_name, patch_port_fwd_entry => $cfg_type_port_fwd_entries_name_patch_patch_port_fwd_entry);

#
# cfg_type_port_fwd_entries_post test
#
# uncomment below and update the test
#my $cfg_type_port_fwd_entries_post_type = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_post_port_fwd_entry = undef; # replace NULL with a proper value
#my $cfg_type_port_fwd_entries_post_result = $api->cfg_type_port_fwd_entries_post(type => $cfg_type_port_fwd_entries_post_type, port_fwd_entry => $cfg_type_port_fwd_entries_post_port_fwd_entry);

#
# cfg_type_wifi_enabled_get test
#
# uncomment below and update the test
#my $cfg_type_wifi_enabled_get_type = undef; # replace NULL with a proper value
#my $cfg_type_wifi_enabled_get_result = $api->cfg_type_wifi_enabled_get(type => $cfg_type_wifi_enabled_get_type);

#
# cfg_type_wifi_get test
#
# uncomment below and update the test
#my $cfg_type_wifi_get_type = undef; # replace NULL with a proper value
#my $cfg_type_wifi_get_result = $api->cfg_type_wifi_get(type => $cfg_type_wifi_get_type);

#
# cfg_type_wifi_patch test
#
# uncomment below and update the test
#my $cfg_type_wifi_patch_type = undef; # replace NULL with a proper value
#my $cfg_type_wifi_patch_wi_fi_settings_request = undef; # replace NULL with a proper value
#my $cfg_type_wifi_patch_result = $api->cfg_type_wifi_patch(type => $cfg_type_wifi_patch_type, wi_fi_settings_request => $cfg_type_wifi_patch_wi_fi_settings_request);

