=begin comment

Quicksilver Web API

Further detail about the available features and configuration options can be found in the User Guide.    # Authorization All API calls use bearer authorization except for the following. - POST /api/user/sessions - Uses basic authorization - GET /api/events - Uses query string authorization  # Errors Since the following errors can happen with any API call or with a broad group of API calls, they are documented here rather than for each API call. - 400 (Bad Request). This may occur for any API call, due to the authorization header being malformed. It may also occur due to malformed or incorrect JSON structure of the request body. Other more specific reasons are documented on a per API basis below. - 401 (Unauthenticated) - 403 (Unauthorized). If the user is authenticated as a user with the Standard role, but the API call requires the Admin role. - 500 (Internal Server Error) 

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::DeviceApi');

my $api = WWW::OpenAPIClient::DeviceApi->new();
isa_ok($api, 'WWW::OpenAPIClient::DeviceApi');

#
# device_backup_available_get test
#
# uncomment below and update the test
#my $device_backup_available_get_result = $api->device_backup_available_get();

#
# device_backup_data_delete test
#
# uncomment below and update the test
#my $device_backup_data_delete_result = $api->device_backup_data_delete();

#
# device_backup_data_get test
#
# uncomment below and update the test
#my $device_backup_data_get_result = $api->device_backup_data_get();

#
# device_certificate_post test
#
# uncomment below and update the test
#my $device_certificate_post_certificate = undef; # replace NULL with a proper value
#my $device_certificate_post_result = $api->device_certificate_post(certificate => $device_certificate_post_certificate);

#
# device_clients_get test
#
# uncomment below and update the test
#my $device_clients_get_result = $api->device_clients_get();

#
# device_export_users_get test
#
# uncomment below and update the test
#my $device_export_users_get_result = $api->device_export_users_get();

#
# device_fw_image_delete test
#
# uncomment below and update the test
#my $device_fw_image_delete_result = $api->device_fw_image_delete();

#
# device_fw_image_get test
#
# uncomment below and update the test
#my $device_fw_image_get_result = $api->device_fw_image_get();

#
# device_fw_image_put test
#
# uncomment below and update the test
#my $device_fw_image_put_content_disposition = undef; # replace NULL with a proper value
#my $device_fw_image_put_body = undef; # replace NULL with a proper value
#my $device_fw_image_put_result = $api->device_fw_image_put(content_disposition => $device_fw_image_put_content_disposition, body => $device_fw_image_put_body);

#
# device_fw_last_update_result_get test
#
# uncomment below and update the test
#my $device_fw_last_update_result_get_result = $api->device_fw_last_update_result_get();

#
# device_fw_update_post test
#
# uncomment below and update the test
#my $device_fw_update_post_result = $api->device_fw_update_post();

#
# device_gps_fix_get test
#
# uncomment below and update the test
#my $device_gps_fix_get_result = $api->device_gps_fix_get();

#
# device_gps_power_get test
#
# uncomment below and update the test
#my $device_gps_power_get_result = $api->device_gps_power_get();

#
# device_import_users_post test
#
# uncomment below and update the test
#my $device_import_users_post_body = undef; # replace NULL with a proper value
#my $device_import_users_post_result = $api->device_import_users_post(body => $device_import_users_post_body);

#
# device_in_safe_mode_get test
#
# uncomment below and update the test
#my $device_in_safe_mode_get_result = $api->device_in_safe_mode_get();

#
# device_info_get test
#
# uncomment below and update the test
#my $device_info_get_result = $api->device_info_get();

#
# device_ird_api_version_get test
#
# uncomment below and update the test
#my $device_ird_api_version_get_result = $api->device_ird_api_version_get();

#
# device_ird_boot_info_get test
#
# uncomment below and update the test
#my $device_ird_boot_info_get_result = $api->device_ird_boot_info_get();

#
# device_ird_constellation_get test
#
# uncomment below and update the test
#my $device_ird_constellation_get_result = $api->device_ird_constellation_get();

#
# device_ird_fw_image_delete test
#
# uncomment below and update the test
#my $device_ird_fw_image_delete_result = $api->device_ird_fw_image_delete();

#
# device_ird_fw_image_get test
#
# uncomment below and update the test
#my $device_ird_fw_image_get_result = $api->device_ird_fw_image_get();

#
# device_ird_fw_image_put test
#
# uncomment below and update the test
#my $device_ird_fw_image_put_content_disposition = undef; # replace NULL with a proper value
#my $device_ird_fw_image_put_body = undef; # replace NULL with a proper value
#my $device_ird_fw_image_put_result = $api->device_ird_fw_image_put(content_disposition => $device_ird_fw_image_put_content_disposition, body => $device_ird_fw_image_put_body);

#
# device_ird_fw_slot_slot_get test
#
# uncomment below and update the test
#my $device_ird_fw_slot_slot_get_slot = undef; # replace NULL with a proper value
#my $device_ird_fw_slot_slot_get_result = $api->device_ird_fw_slot_slot_get(slot => $device_ird_fw_slot_slot_get_slot);

#
# device_ird_fw_update_post test
#
# uncomment below and update the test
#my $device_ird_fw_update_post_body = undef; # replace NULL with a proper value
#my $device_ird_fw_update_post_result = $api->device_ird_fw_update_post(body => $device_ird_fw_update_post_body);

#
# device_ird_hw_get test
#
# uncomment below and update the test
#my $device_ird_hw_get_result = $api->device_ird_hw_get();

#
# device_ird_reports_hwtest_get test
#
# uncomment below and update the test
#my $device_ird_reports_hwtest_get_result = $api->device_ird_reports_hwtest_get();

#
# device_ird_self_test_post test
#
# uncomment below and update the test
#my $device_ird_self_test_post_result = $api->device_ird_self_test_post();

#
# device_ird_sim_get test
#
# uncomment below and update the test
#my $device_ird_sim_get_result = $api->device_ird_sim_get();

#
# device_ird_state_get test
#
# uncomment below and update the test
#my $device_ird_state_get_result = $api->device_ird_state_get();

#
# device_reboot_post test
#
# uncomment below and update the test
#my $device_reboot_post_recovery = undef; # replace NULL with a proper value
#my $device_reboot_post_result = $api->device_reboot_post(recovery => $device_reboot_post_recovery);

#
# device_reset_startup_config_post test
#
# uncomment below and update the test
#my $device_reset_startup_config_post_result = $api->device_reset_startup_config_post();

#
# device_save_runtime_config_post test
#
# uncomment below and update the test
#my $device_save_runtime_config_post_result = $api->device_save_runtime_config_post();

#
# device_time_get test
#
# uncomment below and update the test
#my $device_time_get_result = $api->device_time_get();

#
# device_usage_day_get test
#
# uncomment below and update the test
#my $device_usage_day_get_start = undef; # replace NULL with a proper value
#my $device_usage_day_get_end = undef; # replace NULL with a proper value
#my $device_usage_day_get_result = $api->device_usage_day_get(start => $device_usage_day_get_start, end => $device_usage_day_get_end);

#
# device_usage_delete test
#
# uncomment below and update the test
#my $device_usage_delete_result = $api->device_usage_delete();

#
# device_usage_five_get test
#
# uncomment below and update the test
#my $device_usage_five_get_start = undef; # replace NULL with a proper value
#my $device_usage_five_get_end = undef; # replace NULL with a proper value
#my $device_usage_five_get_result = $api->device_usage_five_get(start => $device_usage_five_get_start, end => $device_usage_five_get_end);

#
# device_usage_hour_get test
#
# uncomment below and update the test
#my $device_usage_hour_get_start = undef; # replace NULL with a proper value
#my $device_usage_hour_get_end = undef; # replace NULL with a proper value
#my $device_usage_hour_get_result = $api->device_usage_hour_get(start => $device_usage_hour_get_start, end => $device_usage_hour_get_end);

#
# device_usage_month_get test
#
# uncomment below and update the test
#my $device_usage_month_get_start = undef; # replace NULL with a proper value
#my $device_usage_month_get_end = undef; # replace NULL with a proper value
#my $device_usage_month_get_result = $api->device_usage_month_get(start => $device_usage_month_get_start, end => $device_usage_month_get_end);

#
# device_usage_year_get test
#
# uncomment below and update the test
#my $device_usage_year_get_start = undef; # replace NULL with a proper value
#my $device_usage_year_get_end = undef; # replace NULL with a proper value
#my $device_usage_year_get_result = $api->device_usage_year_get(start => $device_usage_year_get_start, end => $device_usage_year_get_end);

#
# device_wifi_available_get test
#
# uncomment below and update the test
#my $device_wifi_available_get_result = $api->device_wifi_available_get();

