=begin comment

Quicksilver Web API

Further detail about the available features and configuration options can be found in the User Guide.    # Authorization All API calls use bearer authorization except for the following. - POST /api/user/sessions - Uses basic authorization - GET /api/events - Uses query string authorization  # Errors Since the following errors can happen with any API call or with a broad group of API calls, they are documented here rather than for each API call. - 400 (Bad Request). This may occur for any API call, due to the authorization header being malformed. It may also occur due to malformed or incorrect JSON structure of the request body. Other more specific reasons are documented on a per API basis below. - 401 (Unauthenticated) - 403 (Unauthorized). If the user is authenticated as a user with the Standard role, but the API call requires the Admin role. - 500 (Internal Server Error) 

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::EventsApi');

my $api = WWW::OpenAPIClient::EventsApi->new();
isa_ok($api, 'WWW::OpenAPIClient::EventsApi');

#
# events_id_subscriptions_get test
#
# uncomment below and update the test
#my $events_id_subscriptions_get_id = undef; # replace NULL with a proper value
#my $events_id_subscriptions_get_result = $api->events_id_subscriptions_get(id => $events_id_subscriptions_get_id);

#
# events_id_subscriptions_name_get test
#
# uncomment below and update the test
#my $events_id_subscriptions_name_get_id = undef; # replace NULL with a proper value
#my $events_id_subscriptions_name_get_name = undef; # replace NULL with a proper value
#my $events_id_subscriptions_name_get_result = $api->events_id_subscriptions_name_get(id => $events_id_subscriptions_name_get_id, name => $events_id_subscriptions_name_get_name);

#
# events_id_subscriptions_name_put test
#
# uncomment below and update the test
#my $events_id_subscriptions_name_put_id = undef; # replace NULL with a proper value
#my $events_id_subscriptions_name_put_name = undef; # replace NULL with a proper value
#my $events_id_subscriptions_name_put_body = undef; # replace NULL with a proper value
#my $events_id_subscriptions_name_put_result = $api->events_id_subscriptions_name_put(id => $events_id_subscriptions_name_put_id, name => $events_id_subscriptions_name_put_name, body => $events_id_subscriptions_name_put_body);

#
# events_id_subscriptions_put test
#
# uncomment below and update the test
#my $events_id_subscriptions_put_id = undef; # replace NULL with a proper value
#my $events_id_subscriptions_put_event_name = undef; # replace NULL with a proper value
#my $events_id_subscriptions_put_result = $api->events_id_subscriptions_put(id => $events_id_subscriptions_put_id, event_name => $events_id_subscriptions_put_event_name);

#
# socket_get test
#
# uncomment below and update the test
#my $socket_get_result = $api->socket_get();

