=begin comment

Quicksilver Web API

Further detail about the available features and configuration options can be found in the User Guide.    # Authorization All API calls use bearer authorization except for the following. - POST /api/user/sessions - Uses basic authorization - GET /api/events - Uses query string authorization  # Errors Since the following errors can happen with any API call or with a broad group of API calls, they are documented here rather than for each API call. - 400 (Bad Request). This may occur for any API call, due to the authorization header being malformed. It may also occur due to malformed or incorrect JSON structure of the request body. Other more specific reasons are documented on a per API basis below. - 401 (Unauthenticated) - 403 (Unauthorized). If the user is authenticated as a user with the Standard role, but the API call requires the Admin role. - 500 (Internal Server Error) 

The version of the OpenAPI document: 0.2.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::UserApi');

my $api = WWW::OpenAPIClient::UserApi->new();
isa_ok($api, 'WWW::OpenAPIClient::UserApi');

#
# user_change_password_post test
#
# uncomment below and update the test
#my $user_change_password_post_user_change_password_post_request = undef; # replace NULL with a proper value
#my $user_change_password_post_result = $api->user_change_password_post(user_change_password_post_request => $user_change_password_post_user_change_password_post_request);

#
# user_get test
#
# uncomment below and update the test
#my $user_get_result = $api->user_get();

#
# user_sessions_delete test
#
# uncomment below and update the test
#my $user_sessions_delete_result = $api->user_sessions_delete();

